### ISSUE TITLE
Memory Leak in this gem or in one of it's dependencies.

### ISSUE THREAD

**Issue by onesupercoder** [kosmatov/sidekiq-benchmark#14]
I used this gem with sidekiq 3.3.3, puma 2.11.1, rails 4.2.0, on heroku cedar-14 stack and ran out of memory within minutes.  Removed the gem and everything is working fine now.  I don't have time to diagnose or debug it so I just create this issue to warn others in the future.

That being said, this gem did benchmark my sidekiq worker perfectly!  :+1:  Thank you!

**Comment by baburdick** [comment]
I've been using v0.4.1 of this gem for over 9 months in six different projects (granted: not with puma, and not on Heroku) in Rails 4.1 and 4.2 with sidekiq v3.5.4 and v4.1.4 on Ruby v2.2.4 without memory leak issues. I'm switching to the new v0.5.0 today. I don't expect to see any trouble, but will report back if I do. Have you tried either of these recent versions @onesupercoder?

**Comment by kosmatov** [comment]
Close it because have no similar feedback from other users. Some memory leak issues in sidekiq fixed in last releases
