### ISSUE TITLE
[Feature request] Add configurable expiration time option for statistic data

### ISSUE THREAD

**Issue by rubyconvict** [kosmatov/sidekiq-benchmark#15]
http://redis.io/commands/expire

e.g. using redis gem would be:
```ruby
x.expireat cache_key, expiration
```

**Comment by kosmatov** [comment]
Good option :+1: 
Wait a solution

**Comment by kosmatov** [comment]
Last updates:
* All redis keys expire in 30 days from last update
* If needs to clear some statistic data it's possible in web interface
