### ISSUE TITLE
sinatra-assetpack deprecation: no longer maintained

### ISSUE THREAD

**Issue by baburdick** [kosmatov/sidekiq-benchmark#16]
One of the dependencies of this gem is no longer maintained and now emits a warning upon installation: https://github.com/rstacruz/sinatra-assetpack#readme . The recommended replacements are [sinatra-asset-pipeline](https://github.com/kalasjocke/sinatra-asset-pipeline) and [sprockets-helpers](https://github.com/petebrowne/sprockets-helpers).

**Comment by baburdick** [comment]
Another alternative is to pull in this change from one of the forks: https://github.com/emq/sidekiq-benchmark/commit/54d1be3b44d4999eee00962ef472045d20f9bfde

**Comment by kosmatov** [comment]
Removed

**Comment by baburdick** [comment]
👍 +1 @kosmatov! Thank you, sir.
