### ISSUE TITLE
Bundler could not find compatible versions for gem "sidekiq"

### ISSUE THREAD

**Issue by joshRpowell** [kosmatov/sidekiq-benchmark#22]
@kosmatov great gem. Thank you for putting together. 

When I try and `bundle update sidekiq sidekiq-benchmark` I get this:  

```
Bundler could not find compatible versions for gem "sidekiq":
  In Gemfile:
    sidekiq (= 6.1.2)

    sidekiq-benchmark (= 0.7.0) was resolved to 0.7.0, which depends on
      sidekiq (~> 5)
```

Assuming, because the version tag commit was defined prior to the sidekiq update.

**Comment by kosmatov** [comment]
Hi could you attach your Gemfile?

**Comment by kosmatov** [comment]
Anyway I updated the gem to add support for sidekiq version 6

**Comment by joshRpowell** [comment]
That did the trick. Thank you!
