### ISSUE TITLE
Add sidekiq 7 support

### ISSUE THREAD

**Issue by severinkaelin** [kosmatov/sidekiq-benchmark#24]
Hello

Starting with sidekiq `7.0.0` the `sidekiq-benchmark` gem no longer works. Latest compatible sidekiq version: `6.5.8`.

Error when using the gem alongside sidekiq 7.x (e.g. `7.0.0`, `7.0.2` etc.):

```ruby
Failure/Error: benchmark.finish
TypeError: Unsupported command argument type: Time
```

Resources on sidekiq 7:

- https://github.com/mperham/sidekiq/blob/main/docs/7.0-Upgrade.md
- https://github.com/mperham/sidekiq/blob/main/docs/7.0-API-Migration.md
- https://github.com/mperham/sidekiq/blob/main/docs/capsule.md

Are there any plans to add sidekiq 7 support to this gem? I would like to contribute, but I'm afraid I don't have enough time at the moment.

Thanks a lot.

Kind regards
Severin

**Comment by kosmatov** [comment]
Hi

Thank you for the report, the issue is fixed

**Comment by severinkaelin** [comment]
> Hi
> 
> Thank you for the report, the issue is fixed

@kosmatov Wow, that was fast! Thanks a lot.
